/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MongoDb;


public class App { 
   
   public static void main( String args[] ) {  
   			
   		Dok anu = new Dok();
   		anu.start();
 

   } 
}