/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Mdb;

import java.sql.*;

public class App {

    public static void main( String[] args ) throws SQLException {
        //create connection for a server installed in localhost, with a user "root" with no password
        try (Connection conn = DriverManager.getConnection("jdbc:mariadb://localhost/", "anu", "root")) {
            // create a Statement
            try (Statement stmt = conn.createStatement()) {
                //execute query
                try (ResultSet rs = stmt.executeQuery("SELECT 'Hello World!' as title")) {
                    //position result to first
                    rs.first();
                    System.out.println(rs.getString("title")); //result is "Hello World!"
                }
            }
        }
    }
}