/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Rectangle;

public class App {
    

    public static void main(String[] args) {
        
        Main anu = new Main();
     	anu.mulai();

    }
}
